[project]
name = "hello-python"
version = "0.1.0"
description = "A minimal pyproject.toml"
authors = [ ]
requires-python = ">=3.13"
dependencies = [
  "websockets",
  "pyserial"
  #"aiortc",
  #"av"
]
